name: fastderms
dependencies:
 - python=3.7
 - boost
 - zeromq
 - cmake
 - openpyxl
 - lxml
 - git
 - pandas
 - numpy
 - helics
 - pip
 - pip:
    - OpenDSSDirect.py[extras]
    - subprocess32
    # - --editable=git+https://github.nrel.gov/SETO-foresee/OpenDSS-wrapper.git#egg=feeder
    - --editable=src/dwelling-model
    - --editable=src/helics-runner

channels:
  - defaults
  - gmlc-tdc
